# Generated by Django 6.1.1 on 2026-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
